# config/data_processing.yaml
# Data processing and sampling configuration

# Add this new section
table_selection:
  # Set to 'all' to process all tables, or 'selected' to use specific list
  mode: "selected"  # or "all"
  
  # List of specific tables to process (when mode is 'selected')
  include_tables:
    - "CATALOG_PAGE"
  
  # Optional: exclude specific tables (when mode is 'all')
  exclude_tables:
    - "LARGE_FACT_TABLE"
    - "TEMP_TABLE"

sampling:
  # Disable all sampling to avoid TABLESAMPLE syntax issues
  default_sample_size: 0
  small_table_threshold: 999999999
  medium_table_threshold: 999999999  
  large_table_threshold: 999999999
  
  # Disabled sampling settings (kept for reference)
  # bernoulli_sample_percent: 10
  max_sample_rows: 5000

profiling:
  # These settings will still work without sampling
  max_distinct_values: 50
  batch_size: 10
  column_timeout_seconds: 30
  query_timeout_seconds: 120

text_analysis:
  # Maximum length of sample values string
  max_sample_text_length: 200
  
  # Truncate individual values longer than this
  max_individual_value_length: 50
  
  # Show "..." indicator when truncated
  truncation_indicator: " ... "

numeric_analysis:
  # Precision for numeric statistics
  decimal_places: 2
  
  # Whether to calculate percentiles (expensive for large tables)
  calculate_percentiles: false
  
  # Percentiles to calculate if enabled
  percentiles: [25, 50, 75, 90, 95]

performance:
  # Enable parallel processing of columns
  enable_parallel_processing: false
  
  # Number of worker threads (if parallel enabled)
  max_workers: 4
  
  # Memory limit for sampling operations (MB)
  memory_limit_mb: 1024
  
  # Enable query result caching
  enable_caching: true