# config/data_processing.yaml
# Data processing and sampling configuration

sampling:
  # Default number of rows to sample for large tables
  default_sample_size: 1000
  
  # Table size thresholds for sampling strategy
  small_table_threshold: 10000      # No sampling needed
  medium_table_threshold: 100000    # Use percentage sampling
  large_table_threshold: 1000000    # Use row-based sampling
  
  # Percentage sampling for medium tables
  bernoulli_sample_percent: 10
  
  # For very large tables, use row sampling
  max_sample_rows: 5000

profiling:
  # Maximum distinct values to collect per text column
  max_distinct_values: 50
  
  # Batch size for processing columns
  batch_size: 10
  
  # Timeout for individual column profiling (seconds)
  column_timeout_seconds: 30
  
  # Query timeout for data profiling (seconds)
  query_timeout_seconds: 120

text_analysis:
  # Maximum length of sample values string
  max_sample_text_length: 200
  
  # Truncate individual values longer than this
  max_individual_value_length: 50
  
  # Show "..." indicator when truncated
  truncation_indicator: " ... "

numeric_analysis:
  # Precision for numeric statistics
  decimal_places: 2
  
  # Whether to calculate percentiles (expensive for large tables)
  calculate_percentiles: false
  
  # Percentiles to calculate if enabled
  percentiles: [25, 50, 75, 90, 95]

performance:
  # Enable parallel processing of columns
  enable_parallel_processing: false
  
  # Number of worker threads (if parallel enabled)
  max_workers: 4
  
  # Memory limit for sampling operations (MB)
  memory_limit_mb: 1024
  
  # Enable query result caching
  enable_caching: true